from omni.quantization.compressed_tensors import compressed_tensors
from omni.quantization.npu_w8a8_dynamic import npu_w8a8_dynamic
from omni.quantization.pangu_test import quant_config_pangu_pro_moe